fix makefile bugs and add config_mode test

diff --git a/test/Makefile.in b/test/Makefile.in
--- a/test/Makefile.in
+++ b/test/Makefile.in
@@ -5,7 +5,7 @@ TARGET = @target@
 BUILD = @build@
 nic1 = @nic1@
 nic2 = @nic2@
-ENABLE_DEBUG ="@debug_flag@"
+ENABLE_DEBUG = @debug_flag@
 
 test: all
 all: check tcpprep tcpreplay
@@ -25,7 +25,7 @@ standard:
 	../tcpprep -i test.pcap -o test.regex -r '216.27.178.*' -N client
 
 tcpprep: auto_router auto_bridge cidr regex
-tcpreplay: replay_basic replay_cache replay_cidr replay_trunc replay_pad replay_rand replay_include replay_exclude replay_layer2 replay_packetrate datadump_mode
+tcpreplay: replay_basic replay_cache replay_cidr replay_trunc replay_pad replay_rand replay_include replay_exclude replay_layer2 replay_packetrate datadump_mode config_mode
 
 auto_router:
 	$(PRINTF) "%s" "[tcpprep] Auto/Router mode test: "
@@ -58,55 +58,55 @@ cidr:
 replay_basic:
 	$(PRINTF) "%s" "[tcpreplay] Basic test: "
 	$(PRINTF) "%s\n" "[tcpreplay] Basic test: " >>test.log
-	../tcpreplay $(ENABLE_DEBUG) -i $(nic1) test.pcap >>test.log 2>&1
+	../tcpreplay $(ENABLE_DEBUG) -i $(nic1) -R test.pcap >>test.log 2>&1
 	if [ $? ] ; then $(PRINTF) "\t\t%s\n" "FAILED"; else printf "\t\t%s\n" "OK"; fi
 
 replay_cache:
 	$(PRINTF) "%s" "[tcpreplay] Cache test: "
 	$(PRINTF) "%s\n" "[tcpreplay] Cache test: " >>test.log
-	../tcpreplay $(ENABLE_DEBUG) -c test.cidr -i $(nic1) -j $(nic2) test.pcap >>test.log 2>&1
+	../tcpreplay $(ENABLE_DEBUG) -c test.cidr -i $(nic1) -j $(nic2) -R test.pcap >>test.log 2>&1
 	if [ $? ] ; then $(PRINTF) "\t\t%s\n" "FAILED"; else printf "\t\t%s\n" "OK"; fi
 
 replay_cidr:
 	$(PRINTF) "%s" "[tcpreplay] CIDR test: "
 	$(PRINTF) "%s\n" "[tcpreplay] CIDR test: " >>test.log
-	../tcpreplay $(ENABLE_DEBUG) -C 216.27.178.0/24 -i $(nic1) -j $(nic2) test.pcap >>test.log 2>&1
+	../tcpreplay $(ENABLE_DEBUG) -C 216.27.178.0/24 -i $(nic1) -j $(nic2) -R test.pcap >>test.log 2>&1
 	if [ $? ] ; then $(PRINTF) "\t\t\t%s\n" "FAILED"; else printf "\t\t\t%s\n" "OK"; fi
 
 replay_trunc:
 	$(PRINTF) "%s" "[tcpreplay] Truncate test: "
 	$(PRINTF) "%s\n" "[tcpreplay] Truncate test: " >>test.log
-	../tcpreplay $(ENABLE_DEBUG) -i $(nic1) -u trunc test.pcap >>test.log 2>&1
+	../tcpreplay $(ENABLE_DEBUG) -i $(nic1) -u trunc -R test.pcap >>test.log 2>&1
 	if [ $? ] ; then $(PRINTF) "\t\t%s\n" "FAILED"; else printf "\t\t%s\n" "OK"; fi
 
 replay_pad:
 	$(PRINTF) "%s" "[tcpreplay] Pad test: "
 	$(PRINTF) "%s\n" "[tcpreplay] Pad test: " >>test.log
-	../tcpreplay $(ENABLE_DEBUG) -i $(nic1) -u pad test.pcap >>test.log 2>&1
+	../tcpreplay $(ENABLE_DEBUG) -i $(nic1) -u pad -R test.pcap >>test.log 2>&1
 	if [ $? ] ; then $(PRINTF) "\t\t\t%s\n" "FAILED"; else printf "\t\t\t%s\n" "OK"; fi
 
 replay_rand:
 	$(PRINTF) "%s" "[tcpreplay] Random IP test: "
 	$(PRINTF) "%s\n" "[tcpreplay] Random IP test: " >>test.log
-	../tcpreplay $(ENABLE_DEBUG) -i $(nic1) -s 666 test.pcap >>test.log 2>&1
+	../tcpreplay $(ENABLE_DEBUG) -i $(nic1) -s 666 -R test.pcap >>test.log 2>&1
 	if [ $? ] ; then $(PRINTF) "\t\t%s\n" "FAILED"; else printf "\t\t%s\n" "OK"; fi
 
 replay_include:
 	$(PRINTF) "%s" "[tcpreplay] Include only test: "
 	$(PRINTF) "%s\n" "[tcpreplay] Include only test: " >>test.log
-	../tcpreplay $(ENABLE_DEBUG) -i $(nic1) -x P:1,5,7-53,88,93-100 test.pcap >>test.log 2>&1
+	../tcpreplay $(ENABLE_DEBUG) -i $(nic1) -x P:1,5,7-53,88,93-100 -R test.pcap >>test.log 2>&1
 	if [ $? ] ; then $(PRINTF) "\t\t%s\n" "FAILED"; else printf "\t\t%s\n" "OK"; fi
 
 replay_exclude:
 	$(PRINTF) "%s" "[tcpreplay] Exclude test: "
 	$(PRINTF) "%s\n" "[tcpreplay] Exclude test: " >>test.log
-	../tcpreplay $(ENABLE_DEBUG) -i $(nic1) -X P:1,5,7-53,88,93-100 test.pcap >>test.log 2>&1
+	../tcpreplay $(ENABLE_DEBUG) -i $(nic1) -X P:1,5,7-53,88,93-100 -R test.pcap >>test.log 2>&1
 	if [ $? ] ; then $(PRINTF) "\t\t%s\n" "FAILED"; else printf "\t\t%s\n" "OK"; fi
 
 replay_layer2:
 	$(PRINTF) "%s" "[tcpreplay] Layer2 test: "
 	$(PRINTF) "%s\n" "[tcpreplay] Layer2 test: " >>test.log
-	../tcpreplay $(ENABLE_DEBUG) -i $(nic1) -2 00,50,da,5d,46,55,0,7,eb,30,a4,c3,08,0 test.pcap >>test.log 2>&1
+	../tcpreplay $(ENABLE_DEBUG) -i $(nic1) -2 00,50,da,5d,46,55,0,7,eb,30,a4,c3,08,0 -R test.pcap >>test.log 2>&1
 	if [ $? ] ; then $(PRINTF) "\t\t%s\n" "FAILED"; else printf "\t\t%s\n" "OK"; fi
 
 replay_packetrate:
@@ -118,9 +118,15 @@ replay_packetrate:
 datadump_mode:
 	$(PRINTF) "%s" "[tcpreplay] Data dump mode test: "
 	$(PRINTF) "%s\n" "[tcpreplay] Data dump mode test: " >>test.log
-	../tcpreplay $(ENABLE_DEBUG) -D -i $(nic1) -i $(nic2) -w primary.data -W secondary.data -c test.cidr test.pcap >>test.log 2>&1
+	../tcpreplay $(ENABLE_DEBUG) -D -i $(nic1) -j $(nic2) -w primary.data -W secondary.data -c test.cidr -R test.pcap >>test.log 2>&1
 	if [ $? ] ; then $(PRINTF) "\t%s\n" "FAILED"; else printf "\t%s\n" "OK"; fi
-	
+
+config_mode:
+	$(PRINTF) "%s" "[tcpreplay] Config file mode test: "
+	$(PRINTF) "%s\n" "[tcpreplay] Config file mode test: " >>test.log
+	../tcpreplay $(ENABLE_DEBUG) -f config test.pcap >>test.log 2>&1
+	if [ $? ] ; then $(PRINTF) "\t%s\n" "FAILED"; else printf "\t%s\n" "OK"; fi
+
 clean:
 	rm -f *1 test.log core *~
 
