Bug #422 rewrite port range test (#446)
* #422 litte-endian portmap range test

* #422 big-endian portmap range test

diff --git a/test/Makefile.am b/test/Makefile.am
--- a/test/Makefile.am
+++ b/test/Makefile.am
@@ -23,7 +23,7 @@ EXTRA_DIST = test.pcap test.auto_bridge test.auto_client test.auto_router \
 		test.rewrite_skip test.rewrite_dltuser test.rewrite_dlthdlc \
 		test.rewrite_vlandel test.rewrite_efcs test.rewrite_1ttl \
 		test.rewrite_2ttl test.rewrite_3ttl test.rewrite_enet_subsmac \
-		test.rewrite_mtutrunc test.rewrite_mac_seed \
+		test.rewrite_mtutrunc test.rewrite_mac_seed test.rewrite_range_portmap \
 		test.rewrite_mac_seed_keep test.rewrite_l7fuzzing\
 		test2.rewrite_seed test2.rewrite_portmap test2.rewrite_endpoint \
 		test2.rewrite_pnat test2.rewrite_pad test2.rewrite_trunc \
@@ -33,7 +33,8 @@ EXTRA_DIST = test.pcap test.auto_bridge test.auto_client test.auto_router \
 		test2.rewrite_mtutrunc test2.rewrite_enet_subsmac \
 		test2.rewrite_2ttl test2.rewrite_3ttl test.rewrite_tos test2.rewrite_tos \
 		test2.rewrite_enet_subsmac test2.rewrite_mac_seed \
-		test2.rewrite_mac_seed_keep test2.rewrite_l7fuzzing
+		test2.rewrite_range_portmap test2.rewrite_mac_seed_keep \
+		test2.rewrite_l7fuzzing
 
 test: all
 all: clearlog check tcpprep tcpreplay tcprewrite
@@ -76,6 +77,7 @@ standard_bigendian:
 	$(TCPREWRITE) -i test.pcap -o test.rewrite_seed -s 55
 	$(TCPREWRITE) -i test.pcap -o test.rewrite_tos --tos=50
 	$(TCPREWRITE) -i test.pcap -o test.rewrite_portmap -r 80:8080
+	$(TCPREWRITE) -i test.pcap -o test.rewrite_range_portmap -r 1-100:49148
 	$(TCPREWRITE) -i test.pcap -o test.rewrite_endpoint \
 		-e 10.10.0.1:10.10.0.2 -c test.auto_router
 	$(TCPREWRITE) -i test.pcap -o test.rewrite_pnat \
@@ -116,6 +118,7 @@ standard_littleendian:
 	$(TCPREWRITE) -i test.pcap -o test2.rewrite_seed -s 55
 	$(TCPREWRITE) -i test.pcap -o test2.rewrite_tos --tos=50
 	$(TCPREWRITE) -i test.pcap -o test2.rewrite_portmap -r 80:8080
+	$(TCPREWRITE) -i test.pcap -o test2.rewrite_range_portmap -r 1-100:49148	
 	$(TCPREWRITE) -i test.pcap -o test2.rewrite_endpoint \
 		-e 10.10.0.1:10.10.0.2 -c test.auto_router
 	$(TCPREWRITE) -i test.pcap -o test2.rewrite_pnat \
@@ -156,11 +159,12 @@ tcpprep: auto_router auto_bridge auto_client auto_server auto_first cidr regex \
 	port mac comment print_info print_comment prep_config \
 	mac_reverse cidr_reverse regex_reverse
 
-tcprewrite: rewrite_portmap rewrite_endpoint rewrite_pnat rewrite_trunc \
-	rewrite_pad rewrite_seed rewrite_mac rewrite_layer2 rewrite_config \
-	rewrite_skip rewrite_dltuser rewrite_dlthdlc rewrite_vlandel rewrite_efcs \
-	rewrite_1ttl rewrite_2ttl rewrite_3ttl rewrite_tos rewrite_mtutrunc \
-	rewrite_enet_subsmac rewrite_mac_seed rewrite_mac_seed_keep rewrite_l7fuzzing
+tcprewrite: rewrite_portmap rewrite_range_portmap rewrite_endpoint \
+	rewrite_pnat rewrite_trunc rewrite_pad rewrite_seed rewrite_mac \
+	rewrite_layer2 rewrite_config rewrite_skip rewrite_dltuser rewrite_dlthdlc \
+	rewrite_vlandel rewrite_efcs rewrite_1ttl rewrite_2ttl rewrite_3ttl \
+	rewrite_tos rewrite_mtutrunc rewrite_enet_subsmac rewrite_mac_seed \
+	rewrite_mac_seed_keep rewrite_l7fuzzing
 
 tcpreplay: replay_basic replay_cache replay_pps replay_rate replay_top \
 	replay_config replay_multi replay_pps_multi replay_precache \
@@ -310,6 +314,17 @@ else
 	diff test2.$@ test.$@1 >>test.log 2>&1
 endif
 	if [ $? ] ; then $(PRINTF) "\t\t\t%s\n" "FAILED"; else $(PRINTF) "\t\t\t%s\n" "OK"; fi
+
+rewrite_range_portmap:
+	$(PRINTF) "%s" "[tcprewrite] Portmap range test: "
+	$(PRINTF) "%s\n" "*** [tcprewrite] Portmap range test: " >>test.log
+	$(TCPREWRITE) $(ENABLE_DEBUG) -i test.pcap -o test.$@1 -r 1-100:49148 >>test.log 2>&1
+if WORDS_BIGENDIAN
+	diff test.$@ test.$@1 >>test.log 2>&1
+else
+	diff test2.$@ test.$@1 >>test.log 2>&1
+endif
+	if [ $? ] ; then $(PRINTF) "\t\t\t%s\n" "FAILED"; else $(PRINTF) "\t\t%s\n" "OK"; fi
 
 rewrite_endpoint:
 	$(PRINTF) "%s" "[tcprewrite] Endpoint test: "
