detect if our libpcap has pcap_datalink_val_to_description()

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1322,7 +1322,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 MAJOR_VERSION=2
 MINOR_VERSION=3
-MICRO_VERSION=pre2
+MICRO_VERSION=pre3
 TCPREPLAY_VERSION=$MAJOR_VERSION.$MINOR_VERSION.$MICRO_VERSION
 
 TCPREPLAY_RELEASE=1
@@ -7208,7 +7208,66 @@ echo "$as_me: error: Libpcap versions < 0.6 are no longer supported.
    { (exit 1); exit 1; }; }
 fi
 
+echo "$as_me:$LINENO: checking for pcap_datalink_val_to_description" >&5
+echo $ECHO_N "checking for pcap_datalink_val_to_description... $ECHO_C" >&6
+if test "$cross_compiling" = yes; then
+  have_dlt_to_desc=no
+
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <stdio.h>
+#include "$LPCAPINCDIR/pcap.h"
+int
+main(int argc, char *argv[]) {
+    char name[100];
+    strncpy(name, pcap_datalink_val_to_description(1), 99);
+    exit(0);
+}
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_dlt_to_desc=yes
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+have_dlt_to_desc=no
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+if test $have_dlt_to_desc = yes ; then
+    cat >>confdefs.h <<\_ACEOF
+#define HAVE_DLT_VAL_TO_DESC 1
+_ACEOF
+
+fi
+
 LIBS="$OLDLIBS"
+
+
 
 pcapnav_ver=no
 pcncfg=no
